### PR TITLE
Adding the mailer functionality.

### PR DESCRIPTION
**Pull request by brockwhittaker**
This adds the functionality to the PHP mailer.

### CODE REVIEW

**Comment by JCDJulian** [comment]
Mailer still not working on site. Error:

Uncaught exception 'Swift_RfcComplianceException' with message 'Address in mailbox given [] does not comply with RFC 2822, 3.6.2.' in /home/studiocr/public_html/php/swift/lib/classes/Swift/Mime/Headers/MailboxHeader.php:352

**Comment by brockwhittaker** [comment]
Did you use a valid email? If it has a valid email it works. I've tested it
with both my email and yours.

**Comment by JCDJulian** [comment]
You're correct! It does work when you use a valid email. However, I think the JS should try and do some sort of error handling based on the response. Otherwise the page just hangs for a while and then no feedback is given. I also noticed that it only works when you use https://www.studiocracy.com -- if the www. is not there then it'll think it's a cross-site script. I'm going to try and resolve this by redirection https://studiocracy.com => https://www.studiocracy.com

**Comment by brockwhittaker** [comment]
Yeah I'll implement a validator to knock out bad emails. I'll grab some
email regex and make an error handle. Sorry for the lack of participation.
I've been in SF and just got a new job so I haven't had much time. Sorry
for the inconvenience!

Brock

**Comment by JCDJulian** [comment]
No problem! You've been doing some great work. I'll go ahead and accept this pull request right now and then you can make a separate one for the email validation. I'm pretty sure the Swift PHP mailer already does validation actually so you can just display the alert based on the AJAX response you get. (I know it at least sends a HTTP 500 error when it's not working).

**Comment by brockwhittaker** [comment]
Well I'm going to validate client side so it won't let them send without a
valid email. That'll get rid of all errors unless the client goes into the
JavaScript and submits by changing code.. Which doesn't matter because the
PHP will just throw an error anyways.

And thanks! I plan on doing a bit tomorrow but when I'm back Thursday I'll
play catch up.

**Pull request merged**
