### PR TITLE
Registration modal

### PR DESCRIPTION
**Pull request by japarra**

### CODE REVIEW

**Comment by JCDJulian** [comment]
I'm going to try and merge and resolve this pull request today.

**Comment by japarra** [comment]
It's because I've been rebasing onto master. The commit histories of these branches differ as a result. My fork is able to fast-forward merge onto master though.

**Comment by JCDJulian** [comment]
Okay. But you do want me to merge these changes into the registration-modal branch correct?

**Comment by japarra** [comment]
For demonstration purposes, I opened another pull request, but this time onto studiocracy/master. #57

**Comment by JCDJulian** [comment]
Got it. I'll try and merge this today.

**Comment by japarra** [comment]
AFAIK, merging these changes into the studiocracy/registration-modal branch will cause my unique commits to be duplicated. For example, the commit "add registration form modal" will show up two times, but with different commit SHAs.

**Comment by japarra** [comment]
What if you checked out the studiocracy:registration-modal branch locally and rebased it onto the latest commit of studiocracy:master? Maybe our commit histories will then match.

**Comment by japarra** [comment]
Because the japarra:registration-modal branch has been rebased onto the latest commit of the japarra:master branch, which is even with studiocracy:master.

**Comment by japarra** [comment]
The studiocracy:registration-modal branch is based on an earlier commit of studiocracy:master.

**Comment by JCDJulian** [comment]
I'll try it.

**Comment by JCDJulian** [comment]
Merge conflicts have been resolved. The pull request is in.

**Pull request merged**
