### PR TITLE
Registration modal

### PR DESCRIPTION
**Pull request by japarra**

### CODE REVIEW

**Comment by japarra** [comment]
I think the branches cannot be automatically merged because I've been rebasing my branch on top of new commits from master and the commit SHA's were changed as a result.

**Comment by r-dc** [comment]
I'll check it out

**Comment by r-dc** [comment]
Pull the latest changes and see if you're able to merge them without any trouble. Then reopen another pull request for the registration modal

**Comment by r-dc** [comment]
Also whenever you merge upstream and master make sure to push the changes to your fork.

**Comment by r-dc** [comment]
Also none of the sha's should have changed unless you've been ammending past commits

**Comment by japarra** [comment]
Ok, let me get that sorted out

**Pull request closed without merging**
