### PR TITLE
set default images for posts & users; remove images from seed

### PR DESCRIPTION
**Pull request by r-dc**
set up default assets for posts & user profile images; removed images from posts & users in the seed file (improves performance); gallery does not properly show default images (because the posts have no attached images), not worth fixing if gallery is going to be removed

### CODE REVIEW

**Comment by JCDJulian** [comment]
Can you clarify what you mean about the gallery not showing default images?

**Comment by r-dc** [comment]
The default images aren't attributed to the posts, so post.image_url can't
be used to access it because it doesn't exist

**Comment by r-dc** [comment]
So the gallery is empty

**Comment by JCDJulian** [comment]
I'm still not clear on the issue. You've set the default URL in the posts model, so you should still be able to access the image using post.image

You can't access the image URL, but you can access the default image object which points to that URL.

**Comment by r-dc** [comment]
Post.image.url will get the default, but post.image_url which is used in
the gallery will not (field image_url is empty in db because posts were
created w/o images) so changing gallery to .image.url might fix it. I would
try but I'm on my phone rn

**Comment by r-dc** [comment]
Ok so I just checked again and the gallery is using image.url, so I don't
know why it's not working. Image.url works to get the image elsewhere but
not in the gallery

**Pull request merged**
