### PR TITLE
Comments section almost done

### PR DESCRIPTION
**Pull request by Daven-**
Comment section almost done - progressively smaller containers for each comments when replying, might have to come back to this later.

### CODE REVIEW

**Comment by r-dc** [comment]
Is there a reason you removed the link for deleting comments? Also with the changes you made to the class names the JS for creating and replying to comments broke.

**Comment by r-dc** [comment]
I'm not clear on the purpose of the share link either. Can you sum up the changes you've made and explain them? Thanks!

**Comment by JCDJulian** [comment]
Haven't gotten to test these changes yet but he was just given the design from Alex. We can probably do without that button for now.

**Comment by Daven-** [comment]
So the link_to reply and share buttons don't work for now. The regular reply button should work to reply to comments, I commented it out but then decided against it so that functionality would still be there for test purposes. Until the new buttons work. 

The link to remove comments is still there just commented out and properly commented as to why. Didn't see it in the new design. 

Everything should work like before all other changes are aesthetic.

**Comment by Daven-** [comment]
I guess I deleted the comment for the delete link sorry! But yea I didn't see it in the new design, its still there.

**Comment by JCDJulian** [comment]
This looks awesome. Thanks Daven!

**Pull request merged**
